### PR TITLE
feat(colors): Add Team Fortress 2 Paint Colors

### PR DESCRIPTION
**Pull request by moofemp**
This PR adds all applicable [Paint colors from Team Fortress 2](https://wiki.teamfortress.com/wiki/Paint_Can#Colors).

PR co-authored by @iiboharz, who helped with adapting some names.

Add:
* colour preview "A Mann's Mint" #bcddb3
* colour preview "Aged Moustache Grey" #7e7e7e
* colour preview "Australium Gold" #e7b53b
* colour preview "Blue Team Spirit" #5885a2
* colour preview "Chill of Teamwork" #256d8d
* colour preview "Cold Waterlogged Lab Coat" #839fa3
* colour preview "Cool Air of Debonair" #28394d
* colour preview "Cool Balaclavas Are Forever" #18233d
* colour preview "Cool Cream Spirit" #b88035
* colour preview "Cool Operator's Overalls" #384248
* colour preview "Deep Commitment to Purple" #7d4071
* colour preview "Extraordinary Abundance of Tinge" #e6e6e6
* colour preview "Indubitably Green" #729e42
* colour preview "Mann Orange" (adapted from name "Mann Co. Orange") #cf7336
* colour preview "Muskelmannbraun" #a57545
* colour preview "Noble Hatter's Violet" #51384a
* colour preview "Peculiarly Drab Tincture" #c5af91
* colour preview "Radigan Conagher Brown" #694d3a
* colour preview "Red Team Spirit" #b8383b
* colour preview "Warm Air of Debonair" #654740
* colour preview "Warm Balaclavas Are Forever" #3b1f23
* colour preview "Warm Cream Spirit" #c36c2d
* colour preview "Warm Operator's Overalls" #483838
* colour preview "Warm Waterlogged Lab Coat" #a89a8c
* colour preview "Warmth of Teamwork" #803020
* colour preview "Ye Olde Rustic Colour" #7c6c57
* colour preview "Zepheniah's Greed" #424f3b

Unable to add:
* colour preview "A Color Similar to Slate" #2f4f4f already taken by "Dark Slate Grey"
* colour preview "A Distinctive Lack of Hue" #141414 already taken by "Sooty"
* colour preview "After Eight" #2d2d24 already taken by "Karaka"
* colour preview "Color No. 216-190-216" #d8bed8 in violation with "No enumerations" rule in [CONTRIBUTING.md](https://github.com/meodai/color-names/blob/master/CONTRIBUTING.md#rules-for-new-color-names)
* colour preview "Dark Salmon Injustice" #e9967a already taken by "Kindleflame"
* colour preview "Drably Olive" #808000 already taken by "Heart Gold"
* colour preview "Pink as Hell" #ff69b4 already taken by "Girls Night Out"
* colour preview "The Bitter Taste of Defeat and Lime" #32cd32 already taken by "Poisonous Pesticide"
* colour preview "The Color of a Gentlemann's Business Pants" #f0e68c already taken by "Cornflake"

### CODE REVIEW

**Comment by meodai** [comment]
Such a cool pull-request thanks for that!

I find the names to be a tick long compared to the other names we have. I feel that people still would get the reference, if you would remove the initial "the", "a" and "an". 

For the ones you chose to not add because the the hex value was already taken: Shift those RGB values a bit.

**Comment by moofemp** [comment]
> Such a cool pull-request thanks for that!

:) !

> I find the names to be a tick long compared to the other names we have. I feel that people still would get the reference, if you would remove the initial "the", "a" and "an".

https://github.com/meodai/color-names/pull/116/commits/1756b16b259ffa6abb73941a562d6a476434a642 https://github.com/meodai/color-names/pull/116/commits/506d3778a5ba500cfc937c7c52f333110982e43c https://github.com/meodai/color-names/pull/116/commits/64ace40344186227e93b0988e363576f9b56d183 https://github.com/meodai/color-names/pull/116/commits/0b5bc114554ca1540844b037e9f528789db6d956 https://github.com/meodai/color-names/pull/116/commits/b681f4333d5f3f99f339085889af1e95293ec3ad https://github.com/meodai/color-names/pull/116/commits/7e0ed715b0ec00526d46d915297c7364081cf023  
I've dropped the articles from all except colour preview "A Mann's Mint", since its name is already pretty short.

> For the ones you chose to not add because the the hex value was already taken: Shift those RGB values a bit.

I think since these colours already have names, it's okay to leave the TF2 ones out &mdash; I'm not sure it's helpful to like, shift the actual value over by 1 in the green channel or whatever and have two different names for essentially the same colour. Unless the TF2 colours should take precedence over the existing ones, or a single colour value can be assigned multiple names, I believe the best solution is to leave them out.

**Comment by meodai** [comment]
@moofemp I would shift more shift each channel a bit. It's good to have a great variety of names. Should I merge it like it is? Or do you want to shift the values of the missing ones?

**Comment by meodai** [comment]
@moofemp ping

**Comment by meodai** [comment]
@moofemp its in. I have added the ones you did not include: https://github.com/meodai/color-names/commit/099218010e211a38d9090ebb3233ea55220cf023

**Comment by moofemp** [comment]
> @moofemp ping

Hey, sorry I was unresponsive for a bit. I was on a trip to Germany and forgot to take my passwords with me. Oops.

Thank you for taking care of and merging everything!

**Comment by meodai** [comment]
@moofemp no worries! I was just not too keen on manually merging. Thanks for the very clean pull-request.

**Pull request merged**
