### PR TITLE
added #2c75ff

### PR DESCRIPTION
**Pull request by cheesits456**
its a really nice shade of blue i discovered a couple years ago, and it's become the main color used for my largest project, which has an audience of over 1,000,000 users

### CODE REVIEW

**Comment by meodai** [comment]
Thank you for your submission! 

I don't feel too comfortable adding a product name as a color. I want to avoid using this list for promotion purposes. I would feel more comfortable if the color would just be called something like "Hailey Blue". It would sound more generic of course, but I would not mind.

Please also make sure to sort the source csv: https://github.com/meodai/color-names/pull/85/commits/5f72d078c02f5bc313669583fc56f75c77786f82#diff-f8e20f9b51491107ebd7eced0273bc8d You can use a simple js sort using local compare: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

**Comment by cheesits456** [comment]
I agree with your suggestion for the name - as for the csv sorting, `CONTRIBUTING.md` didn't specify that the new entry should be placed in the correct spot alphabetically, so I assumed that the build script would sort the file automatically when it runs. If you'd like, I can provide the modified build script I used in another PR. 

That being said, all the issues mentioned have been fixed, and I believe this PR is good to merge :)

**Comment by basgys** [comment]
@meodai `CONTRIBUTING.md` does not give details about product names. It says "No protected brand-names", but what about unprotected product names like HaileyBot? Some names could refer to popular open-source project or pop culture items (e.g. Diva Mecha, which refers to the D.Va character in Overwatch). 

In my opinion, the most important is the motivation that lies behind the addition of a new name. It must not benefit anybody to have a colour name in the dictionary. We could have a set of moral principles in `CONTRIBUTING.md`, such as "Using color-names to promote products or brands is strictly forbidden". The problem is that it is hard to verify.

That brings me to the last part. We also should think about having rules to evict colours from the repository in case we realise too late or if a name becomes a protected brand name?

**Comment by basgys** [comment]
@meodai We can get inspiration from Wiktionary or other collaborative dictionaries.

### Company names
Being a company name does not guarantee inclusion. To be included, the use of the company name other than its use as a trademark (i.e., a use as a common word or family name) has to be attested. 

> If HaleyBot becomes a popular term that refers to a colour, we could think about including it perhaps?

### Attestation vs. the slippery slope
There is occasionally concern that adding an entry for a particular term will lead to entries for a large number of similar terms. This is not a problem, as each term is considered on its own based on its usage, not on the usage of terms similar in form.

> It is a good idea to mention that having product names or pop culture items does not guarantee the inclusion of similar terms.

Source [Criteria for inclusion](https://en.wiktionary.org/wiki/Wiktionary:Criteria_for_inclusion)

**Comment by meodai** [comment]
@cheesits456 good point I will add it there.

**Comment by meodai** [comment]
@basgys This list is often used by people generating style guides. I would hate it to have a "Drupal Blue" or "Wordpress Black" in there. But I like your proposal from Wiktionary, I will create a pull request with it. PS: Thanks for your contribution @cheesits456, feel free to think of other original color names ;)

**Pull request merged**
