### PR TITLE
Add color-octree for color search

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by caub** [comment]
Hey thanks, I added docs and tests (not finished)

My ony concern is the initialization time is a bit slow with your package ([file](https://github.com/caub/color-octree/blob/master/index.spec.js))
```
add: 2538.887ms
add2: 26126.007ms
closest2: 12.136ms
add3: 27244.745ms (color-name-list)
closest3: 0.197ms
```

search is faster yes, that was the goal

I could also memoize searches, but it's simple to wrap it with lodash.memoize for example, if it works well, you could use it for https://color-names.herokuapp.com

Best

**Comment by meodai** [comment]
Oh ok we can also keep how it is for now on the server. Will you adapt the pull request with the changes to the readme? Thanks again!

**Comment by caub** [comment]
@meodai done for the readme

>  I wanted a possibility to return each color names only once

you mean having this kind of behavior:?
```js
console.log(closest('#abdcef") // {name: 'Foo', hex: '#abddff', d: 58}
console.log(closest('#abdcef") // {name: 'Foo', hex: '#acdcfe', d: 62}
```

**Comment by meodai** [comment]
@caub yes this it is that what I meant. (+ you would need a method to reset it)

**Comment by caub** [comment]
I started adding a `delete` method, to remove an entry, but what's actually the usecase for what you described?

Maybe finding the n first matches, ordered? because that can be done more simply

**Comment by meodai** [comment]
yeah there is a use case for that. Lets say you generate a styleguide for colors a company and two of those colors are close together. It would not be nice if they would be called the same.

**Comment by caub** [comment]
Ok, added `remove` https://github.com/caub/color-octree/blob/master/index.spec.js#L47-L75

**Comment by meodai** [comment]
Cool! What about my other comments?

**Comment by caub** [comment]
What else doesn't it do? `init` is for resetting

**Comment by meodai** [comment]
@caub I made multiple comments to the readme.md pull-request. You can find them below my original comment

**Comment by caub** [comment]
@meodai I don't see them: https://github.com/meodai/color-names/pull/32/commits/9bb283393c8c7dc6d21a0a14ea7641bc0d993049

**Comment by caub** [comment]
Ah thanks

- for point 1 and 2, I fixed it I hope, and I mention it at the beginning, I remember you told me to replace nearest-color by it when initially I had put both variants, it's like you want.
- any hex format is handled https://github.com/caub/color-octree/blob/master/index.spec.js#L6-L10

The mention to DeltaE is interesting, it'd be possible to use any other color-models, not just rgb in color-octree, will look at it

ps: would be curious to know how you saw those past reviews

**Comment by meodai** [comment]
@caub thanks a lot for your contribution!

**Pull request merged**
